parserOptions:
  ecmaVersion: 2017
extends: [ 'airbnb-base' ]
rules:
  semi: [ "error", "always"]
  quotes: [ "error", "single"]
  comma-spacing: [ "error", { before: false, after: true }]
  indent: [ 'error', 2 ]
  arrow-parens: [ "error", "always"]
  max-len: [ 'warn', 160 ]
  strict: off
  no-console: off
  no-unused-vars: off
  complexity: ["error", { "max": 5 }]
  max-lines-per-function: ["error", { "max": 25, "skipBlankLines": true }]
  import/prefer-default-export: false
  import/no-extraneous-dependencies: ["error", {"peerDependencies": true}] # XXX https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md
env:
  jest: true
  node: true
  es6: true

